// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_pHufUoDMoEun85RK0WzeNx6pHIX81HI',
    appId: '1:423869355068:web:8c6a7e298c581e979f9f39',
    messagingSenderId: '423869355068',
    projectId: 'reddit-clone-73da4',
    authDomain: 'reddit-clone-73da4.firebaseapp.com',
    storageBucket: 'reddit-clone-73da4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKpjTM_USFSyQHPUqmLoSdRY8zr8KKhLM',
    appId: '1:423869355068:android:1b382d9faa0725969f9f39',
    messagingSenderId: '423869355068',
    projectId: 'reddit-clone-73da4',
    storageBucket: 'reddit-clone-73da4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWENml4tmI2O1xmRTy5G3B8ZHaxJJGCfI',
    appId: '1:423869355068:ios:f7ecadddad23b2469f9f39',
    messagingSenderId: '423869355068',
    projectId: 'reddit-clone-73da4',
    storageBucket: 'reddit-clone-73da4.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWENml4tmI2O1xmRTy5G3B8ZHaxJJGCfI',
    appId: '1:423869355068:ios:446ee8e141fb4fe09f9f39',
    messagingSenderId: '423869355068',
    projectId: 'reddit-clone-73da4',
    storageBucket: 'reddit-clone-73da4.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
